// Generates src/data/toolsLite.ts — a lightweight projection of the merged tool
// data (card/list/filter fields only), so list and edge routes don't bundle the
// heavy per-tool content. Run after any tool-data change:
//   npx tsx scripts/build_tools_lite.mts
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { tools } from '../src/data/tools.ts';
import type { Tool, ToolLite } from '../src/types/index.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT = path.join(__dirname, '..', 'src', 'data', 'toolsLite.ts');

const slim = (t: Tool): ToolLite => {
  const lite: ToolLite = {
    id: t.id,
    name: t.name,
    slug: t.slug,
    description: t.description,
    categoryId: t.categoryId,
    pricingType: t.pricingType,
    rating: t.rating,
    beginnerFriendly: t.beginnerFriendly,
    koreanSupport: t.koreanSupport,
    mobileSupport: t.mobileSupport,
    commercialUse: t.commercialUse,
    featured: t.featured,
    tags: t.tags,
    websiteUrl: t.websiteUrl,
  };
  if (t.beginnerDescription) lite.beginnerDescription = t.beginnerDescription;
  if (t.affiliateUrl) lite.affiliateUrl = t.affiliateUrl;
  if (t.logoUrl) lite.logoUrl = t.logoUrl;
  if (t.startingPrice) lite.startingPrice = t.startingPrice;
  if (t.verified) lite.verified = t.verified;
  if (t.korea) lite.korea = t.korea;
  return lite;
};

const lite = tools.map(slim);
const body = lite.map((t) => JSON.stringify(t)).join(',\n  ');
const file = `import { ToolLite } from '../types';\n\n` +
  `// AUTO-GENERATED by scripts/build_tools_lite.mts — do not edit by hand.\n` +
  `// Lightweight tool data (card/filter fields) for list and edge routes.\n` +
  `export const toolsLite: ToolLite[] = [\n  ${body}\n];\n\nexport default toolsLite;\n`;

fs.writeFileSync(OUTPUT, file, 'utf8');
console.log(`Wrote ${lite.length} lite tools to ${OUTPUT}`);
