// One-off fixer: replaces placeholder Google-search websiteUrl values in
// src/data/generatedTools.ts with each tool's real official website.
// Usage: node scripts/fix_website_urls.js
const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, '..', 'src', 'data', 'generatedTools.ts');

const URL_MAP = {
  'ChatGPT': 'https://chatgpt.com',
  'Claude': 'https://claude.ai',
  'Gemini': 'https://gemini.google.com',
  'Perplexity': 'https://www.perplexity.ai',
  'Microsoft Copilot': 'https://copilot.microsoft.com',
  'Grok': 'https://grok.com',
  'Poe': 'https://poe.com',
  'You.com': 'https://you.com',
  'Phind': 'https://www.phind.com',
  'HuggingChat': 'https://huggingface.co/chat/',
  'Jasper': 'https://www.jasper.ai',
  'Copy.ai': 'https://www.copy.ai',
  'Writesonic': 'https://writesonic.com',
  'Rytr': 'https://rytr.me',
  'Anyword': 'https://www.anyword.com',
  'Grammarly': 'https://www.grammarly.com',
  'QuillBot': 'https://quillbot.com',
  'Wordtune': 'https://www.wordtune.com',
  'Sudowrite': 'https://www.sudowrite.com',
  'HyperWrite': 'https://www.hyperwriteai.com',
  'Notion AI': 'https://www.notion.com/product/ai',
  'Craft AI': 'https://www.craft.do',
  'Lex': 'https://lex.page',
  'Frase': 'https://www.frase.io',
  'Surfer AI': 'https://surferseo.com',
  'Semrush SEO Writing Assistant': 'https://www.semrush.com/swa/',
  'Conductor AI Writing Assistant': 'https://www.conductor.com',
  'Writer': 'https://writer.com',
  'Simplified': 'https://simplified.com',
  'Neuroflash': 'https://neuroflash.com',
  'Elicit': 'https://elicit.com',
  'Consensus': 'https://consensus.app',
  'Semantic Scholar': 'https://www.semanticscholar.org',
  'Scite': 'https://scite.ai',
  'Research Rabbit': 'https://www.researchrabbit.ai',
  'Connected Papers': 'https://www.connectedpapers.com',
  'Google Scholar': 'https://scholar.google.com',
  'NotebookLM': 'https://notebooklm.google.com',
  'Genei': 'https://www.genei.io',
  'Humata AI': 'https://www.humata.ai',
  'ChatPDF': 'https://www.chatpdf.com',
  'SciSpace': 'https://scispace.com',
  'Scholarcy': 'https://www.scholarcy.com',
  'AskYourPDF': 'https://askyourpdf.com',
  'Perlego AI': 'https://www.perlego.com',
  'You.com Research': 'https://you.com',
  'Komo Search': 'https://komo.ai',
  'Andi': 'https://andisearch.com',
  'Exa': 'https://exa.ai',
  'Midjourney': 'https://www.midjourney.com',
  'ChatGPT Image': 'https://chatgpt.com',
  'DALL·E': 'https://openai.com/index/dall-e-3/',
  'Adobe Firefly': 'https://www.adobe.com/products/firefly.html',
  'Leonardo AI': 'https://leonardo.ai',
  'Ideogram': 'https://ideogram.ai',
  'Stable Diffusion': 'https://stability.ai',
  'DreamStudio': 'https://dreamstudio.ai',
  'FLUX': 'https://bfl.ai',
  'Canva AI': 'https://www.canva.com/ai/',
  'Freepik AI': 'https://www.freepik.com/ai',
  'Krea AI': 'https://www.krea.ai',
  'Playground AI': 'https://playground.com',
  'NightCafe': 'https://creator.nightcafe.studio',
  'BlueWillow': 'https://www.bluewillow.ai',
  'Mage.space': 'https://www.mage.space',
  'Clipdrop': 'https://clipdrop.co',
  'Recraft': 'https://www.recraft.ai',
  'Pebblely': 'https://pebblely.com',
  'Photoroom': 'https://www.photoroom.com',
  'Photoshop Generative Fill': 'https://www.adobe.com/products/photoshop/generative-fill.html',
  'Lightroom AI': 'https://www.adobe.com/products/photoshop-lightroom.html',
  'Luminar Neo': 'https://skylum.com/luminar',
  'Topaz Photo AI': 'https://www.topazlabs.com/topaz-photo-ai',
  'Remini': 'https://remini.ai',
  'Let’s Enhance': 'https://letsenhance.io',
  'Upscale.media': 'https://www.upscale.media',
  'Remove.bg': 'https://www.remove.bg',
  'Cleanup.pictures': 'https://cleanup.pictures',
  'Pixelcut': 'https://www.pixelcut.ai',
  'Fotor AI': 'https://www.fotor.com',
  'Picsart AI': 'https://picsart.com',
  'Magnific AI': 'https://magnific.ai',
  'Leonardo Canvas': 'https://leonardo.ai',
  'Runway Image Tools': 'https://runwayml.com',
  'OpenArt': 'https://openart.ai',
  'Canva': 'https://www.canva.com',
  'Adobe Express': 'https://www.adobe.com/express/',
  'Microsoft Designer': 'https://designer.microsoft.com',
  'Figma AI': 'https://www.figma.com/ai/',
  'Uizard': 'https://uizard.io',
  'Galileo AI': 'https://www.usegalileo.ai',
  'Visily': 'https://www.visily.ai',
  'Khroma': 'https://www.khroma.co',
  'Looka': 'https://looka.com',
  'Brandmark': 'https://brandmark.io',
  'Designs.ai': 'https://designs.ai',
  'LogoAI': 'https://www.logoai.com',
  'Flair AI': 'https://flair.ai',
  'Mokker AI': 'https://mokker.ai',
  'Booth AI': 'https://www.booth.ai',
  'AdCreative.ai': 'https://www.adcreative.ai',
  'Creatopy': 'https://www.creatopy.com',
  'Predis.ai': 'https://predis.ai',
  'Ocoya': 'https://www.ocoya.com',
  'Sora': 'https://sora.com',
  'Runway': 'https://runwayml.com',
  'Google Veo': 'https://deepmind.google/technologies/veo/',
  'Pika': 'https://pika.art',
  'Kling AI': 'https://klingai.com',
  'Luma Dream Machine': 'https://lumalabs.ai/dream-machine',
  'PixVerse': 'https://pixverse.ai',
  'Haiper': 'https://haiper.ai',
  'Kaiber': 'https://kaiber.ai',
  'Synthesia': 'https://www.synthesia.io',
  'HeyGen': 'https://www.heygen.com',
  'D-ID': 'https://www.d-id.com',
  'Colossyan': 'https://www.colossyan.com',
  'Elai.io': 'https://elai.io',
  'DeepBrain AI': 'https://www.aistudios.com',
  'InVideo AI': 'https://invideo.io',
  'Pictory': 'https://pictory.ai',
  'Lumen5': 'https://lumen5.com',
  'Fliki': 'https://fliki.ai',
  'Kapwing AI': 'https://www.kapwing.com',
  'Descript': 'https://www.descript.com',
  'CapCut AI': 'https://www.capcut.com',
  'OpusClip': 'https://www.opus.pro',
  'Vidyo.ai': 'https://vidyo.ai',
  'Vizard.ai': 'https://vizard.ai',
  'Klap': 'https://klap.app',
  'Captions.ai': 'https://www.captions.ai',
  'Submagic': 'https://www.submagic.co',
  'VEED.io': 'https://www.veed.io',
  'Wisecut': 'https://www.wisecut.video',
  'Riverside': 'https://riverside.fm',
  'Unscreen': 'https://www.unscreen.com',
  'Topaz Video AI': 'https://www.topazlabs.com/topaz-video-ai',
  'Filmora AI': 'https://filmora.wondershare.com',
  'Adobe Premiere Pro AI': 'https://www.adobe.com/products/premiere.html',
  'DaVinci Resolve AI': 'https://www.blackmagicdesign.com/products/davinciresolve',
  'AutoPod': 'https://www.autopod.fm',
  'Gling AI': 'https://www.gling.ai',
  'FireCut': 'https://firecut.ai',
  'ElevenLabs': 'https://elevenlabs.io',
  'PlayHT': 'https://play.ht',
  'Murf AI': 'https://murf.ai',
  'WellSaid Labs': 'https://wellsaidlabs.com',
  'LOVO AI': 'https://lovo.ai',
  'Speechify': 'https://speechify.com',
  'NaturalReader': 'https://www.naturalreaders.com',
  'Resemble AI': 'https://www.resemble.ai',
  'Replica Studios': 'https://replicastudios.com',
  'Altered Studio': 'https://www.altered.ai',
  'Typecast': 'https://typecast.ai',
  'Naver Clova Dubbing': 'https://clovadubbing.naver.com',
  'Google Cloud TTS': 'https://cloud.google.com/text-to-speech',
  'Amazon Polly': 'https://aws.amazon.com/polly/',
  'Azure AI Speech': 'https://azure.microsoft.com/en-us/products/ai-services/ai-speech',
  'Listnr': 'https://listnr.ai',
  'Voicemaker': 'https://voicemaker.in',
  'Dubverse': 'https://dubverse.ai',
  'Rask AI': 'https://www.rask.ai',
  'Papercup': 'https://www.papercup.com',
  'Suno': 'https://suno.com',
  'Udio': 'https://www.udio.com',
  'AIVA': 'https://www.aiva.ai',
  'Soundraw': 'https://soundraw.io',
  'Beatoven.ai': 'https://www.beatoven.ai',
  'Mubert': 'https://mubert.com',
  'Boomy': 'https://boomy.com',
  'Loudly': 'https://www.loudly.com',
  'Stable Audio': 'https://stableaudio.com',
  'MusicGen': 'https://audiocraft.metademolab.com',
  'Riffusion': 'https://www.riffusion.com',
  'Splash Pro': 'https://www.splashmusic.com',
  'Ecrett Music': 'https://ecrettmusic.com',
  'Amper Music': 'https://www.shutterstock.com/discover/ampermusic',
  'Soundful': 'https://soundful.com',
  'WavTool': 'https://wavtool.com',
  'Moises AI': 'https://moises.ai',
  'Lalal.ai': 'https://www.lalal.ai',
  'AudioStrip': 'https://www.audiostrip.co.uk',
  'BandLab AI': 'https://www.bandlab.com',
  'ChatGPT Codex': 'https://chatgpt.com/codex',
  'Claude Code': 'https://claude.com/claude-code',
  'Cursor': 'https://cursor.com',
  'GitHub Copilot': 'https://github.com/features/copilot',
  'Windsurf': 'https://windsurf.com',
  'Replit Agent': 'https://replit.com',
  'Bolt.new': 'https://bolt.new',
  'Lovable': 'https://lovable.dev',
  'v0 by Vercel': 'https://v0.dev',
  'Codeium / Windsurf': 'https://windsurf.com',
  'Tabnine': 'https://www.tabnine.com',
  'Amazon Q Developer': 'https://aws.amazon.com/q/developer/',
  'Sourcegraph Cody': 'https://sourcegraph.com/cody',
  'CodeRabbit': 'https://www.coderabbit.ai',
  'Sweep AI': 'https://sweep.dev',
  'Devin': 'https://devin.ai',
  'Cline': 'https://cline.bot',
  'Roo Code': 'https://roocode.com',
  'Continue': 'https://www.continue.dev',
  'Aider': 'https://aider.chat',
  'OpenAI API': 'https://platform.openai.com',
  'Anthropic API': 'https://www.anthropic.com/api',
  'Google Gemini API': 'https://ai.google.dev',
  'Mistral AI': 'https://mistral.ai',
  'Cohere': 'https://cohere.com',
  'Groq': 'https://groq.com',
  'Together AI': 'https://www.together.ai',
  'Replicate': 'https://replicate.com',
  'Hugging Face': 'https://huggingface.co',
  'Fireworks AI': 'https://fireworks.ai',
  'Perplexity API': 'https://docs.perplexity.ai',
  'Stability AI API': 'https://platform.stability.ai',
  'ElevenLabs API': 'https://elevenlabs.io/api',
  'Runway API': 'https://dev.runwayml.com',
  'AssemblyAI': 'https://www.assemblyai.com',
  'Deepgram': 'https://deepgram.com',
  'Pinecone': 'https://www.pinecone.io',
  'Weaviate': 'https://weaviate.io',
  'Chroma': 'https://www.trychroma.com',
  'Supabase Vector': 'https://supabase.com/modules/vector',
  'Framer AI': 'https://www.framer.com',
  'Wix AI': 'https://www.wix.com',
  'Webflow AI': 'https://webflow.com',
  'Durable': 'https://durable.co',
  '10Web': 'https://10web.io',
  'Hostinger AI Website Builder': 'https://www.hostinger.com/website-builder',
  'GoDaddy AI Website Builder': 'https://www.godaddy.com/websites/website-builder',
  'Relume': 'https://www.relume.io',
  'Dora AI': 'https://www.dora.run',
  'Typedream': 'https://typedream.com',
  'Carrd': 'https://carrd.co',
  'Gamma': 'https://gamma.app',
  'Softr': 'https://www.softr.io',
  'Bubble AI': 'https://bubble.io',
  'Glide AI': 'https://www.glideapps.com',
  'Pory': 'https://pory.io',
  'Webstudio': 'https://webstudio.is',
  'TeleportHQ': 'https://teleporthq.io',
  'Builder.io AI': 'https://www.builder.io',
  'Locofy': 'https://www.locofy.ai',
  'Zapier': 'https://zapier.com',
  'Make': 'https://www.make.com',
  'n8n': 'https://n8n.io',
  'Gumloop': 'https://www.gumloop.com',
  'Relay.app': 'https://www.relay.app',
  'IFTTT': 'https://ifttt.com',
  'Pipedream': 'https://pipedream.com',
  'Bardeen': 'https://www.bardeen.ai',
  'Lindy AI': 'https://www.lindy.ai',
  'Relevance AI': 'https://relevanceai.com',
  'CrewAI': 'https://www.crewai.com',
  'LangChain': 'https://www.langchain.com',
  'LangGraph': 'https://www.langchain.com/langgraph',
  'AutoGen': 'https://microsoft.github.io/autogen/',
  'Flowise': 'https://flowiseai.com',
  'Dify': 'https://dify.ai',
  'Voiceflow': 'https://www.voiceflow.com',
  'Botpress': 'https://botpress.com',
  'Stack AI': 'https://www.stack-ai.com',
  'AgentOps': 'https://www.agentops.ai',
  'Otter.ai': 'https://otter.ai',
  'Fireflies.ai': 'https://fireflies.ai',
  'Fathom': 'https://fathom.video',
  'tl;dv': 'https://tldv.io',
  'Notta': 'https://www.notta.ai',
  'Krisp': 'https://krisp.ai',
  'Avoma': 'https://www.avoma.com',
  'Sembly AI': 'https://www.sembly.ai',
  'MeetGeek': 'https://meetgeek.ai',
  'Supernormal': 'https://supernormal.com',
  'Granola': 'https://www.granola.ai',
  'Jamie': 'https://www.meetjamie.ai',
  'Read AI': 'https://www.read.ai',
  'Circleback': 'https://circleback.ai',
  'Tactiq': 'https://tactiq.io',
  'Fellow AI': 'https://fellow.app',
  'Rewatch': 'https://rewatch.com',
  'Grain': 'https://grain.com',
  'Tome': 'https://tome.app',
  'Beautiful.ai': 'https://www.beautiful.ai',
  'Canva Docs/Presentations': 'https://www.canva.com/presentations/',
  'Microsoft Copilot PowerPoint': 'https://www.microsoft.com/en-us/microsoft-365/powerpoint',
  'Google Gemini for Slides': 'https://workspace.google.com/products/slides/',
  'Pitch': 'https://pitch.com',
  'Decktopus': 'https://www.decktopus.com',
  'SlidesAI': 'https://www.slidesai.io',
  'Plus AI': 'https://plusai.com',
  'Humata': 'https://www.humata.ai',
  'PDF.ai': 'https://pdf.ai',
  'UPDF AI': 'https://updf.com',
  'Adobe Acrobat AI Assistant': 'https://www.adobe.com/acrobat/generative-ai-pdf.html',
  'Documind': 'https://documind.chat',
  'Unriddle': 'https://www.unriddle.ai',
  'Explainpaper': 'https://www.explainpaper.com',
  'Harvey': 'https://www.harvey.ai',
  'Spellbook': 'https://www.spellbook.legal',
  'Lawgeex': 'https://www.lawgeex.com',
  'Luminance': 'https://www.luminance.com',
  'Casetext CoCounsel': 'https://casetext.com',
  'Lexis+ AI': 'https://www.lexisnexis.com/en-us/products/lexis-plus-ai.page',
  'Westlaw Precision AI': 'https://legal.thomsonreuters.com/en/products/westlaw',
  'Ironclad AI': 'https://ironcladapp.com',
  'Juro AI': 'https://juro.com',
  'Evisort': 'https://www.evisort.com',
  'LinkSquares': 'https://linksquares.com',
  'LegalOn': 'https://www.legalontech.com',
  'Robin AI': 'https://www.robinai.com',
  'DocuSign AI': 'https://www.docusign.com',
  'PandaDoc AI': 'https://www.pandadoc.com',
  'HubSpot AI': 'https://www.hubspot.com/products/artificial-intelligence',
  'Salesforce Einstein': 'https://www.salesforce.com/artificial-intelligence/',
  'Clay': 'https://www.clay.com',
  'Apollo AI': 'https://www.apollo.io',
  'Lavender': 'https://www.lavender.ai',
  'Instantly AI': 'https://instantly.ai',
  'Smartlead': 'https://www.smartlead.ai',
  'Lemlist': 'https://www.lemlist.com',
  'Pencil': 'https://www.trypencil.com',
  'Hootsuite OwlyWriter': 'https://www.hootsuite.com/platform/owly-writer-ai',
  'Buffer AI': 'https://buffer.com/ai-assistant',
  'Taplio': 'https://taplio.com',
  'Tweet Hunter': 'https://tweethunter.io',
  'PhantomBuster': 'https://phantombuster.com',
  'Browse AI': 'https://www.browse.ai',
  'Semrush': 'https://www.semrush.com',
  'Ahrefs': 'https://ahrefs.com',
  'Surfer SEO': 'https://surferseo.com',
  'Clearscope': 'https://www.clearscope.io',
  'MarketMuse': 'https://www.marketmuse.com',
  'NeuronWriter': 'https://neuronwriter.com',
  'Scalenut': 'https://www.scalenut.com',
  'SE Ranking': 'https://seranking.com',
  'LowFruits': 'https://lowfruits.io',
  'WriterZen': 'https://writerzen.net',
  'KoalaWriter': 'https://koala.sh',
  'Autoblogging.ai': 'https://autoblogging.ai',
  'ContentShake AI': 'https://www.semrush.com/contentshake/',
  'RankIQ': 'https://www.rankiq.com',
  'Page Optimizer Pro': 'https://pageoptimizer.pro',
  'Surfer AI Humanizer': 'https://surferseo.com',
  'Originality.ai': 'https://originality.ai',
  'Content at Scale': 'https://contentatscale.ai',
  'ChatGPT Advanced Data Analysis': 'https://chatgpt.com',
  'Microsoft Copilot Excel': 'https://www.microsoft.com/en-us/microsoft-365/excel',
  'Google Gemini Sheets': 'https://workspace.google.com/products/sheets/',
  'Rows AI': 'https://rows.com',
  'Numerous.ai': 'https://numerous.ai',
  'SheetAI': 'https://www.sheetai.app',
  'Akkio': 'https://www.akkio.com',
  'Julius AI': 'https://julius.ai',
  'Polymer': 'https://www.polymersearch.com',
  'Obviously AI': 'https://www.obviously.ai',
  'DataRobot': 'https://www.datarobot.com',
  'Tableau AI': 'https://www.tableau.com',
  'Power BI Copilot': 'https://www.microsoft.com/en-us/power-platform/products/power-bi',
  'ThoughtSpot Sage': 'https://www.thoughtspot.com',
  'Hex': 'https://hex.tech',
  'Mode AI': 'https://mode.com',
  'Databricks Assistant': 'https://www.databricks.com',
  'Snowflake Cortex': 'https://www.snowflake.com/en/data-cloud/cortex/',
  'BigQuery Gemini': 'https://cloud.google.com/bigquery',
  'MonkeyLearn': 'https://monkeylearn.com',
  'Intercom Fin': 'https://www.intercom.com/fin',
  'Zendesk AI': 'https://www.zendesk.com/service/ai/',
  'Freshdesk Freddy AI': 'https://www.freshworks.com/freddy-ai/',
  'Help Scout AI': 'https://www.helpscout.com',
  'Tidio': 'https://www.tidio.com',
  'Drift': 'https://www.drift.com',
  'Ada': 'https://www.ada.cx',
  'Forethought': 'https://forethought.ai',
  'Kustomer AI': 'https://www.kustomer.com',
  'Crisp AI': 'https://crisp.chat',
  'Manychat AI': 'https://manychat.com',
  'Chatbase': 'https://www.chatbase.co',
  'CustomGPT': 'https://customgpt.ai',
  'SiteGPT': 'https://sitegpt.ai',
  'DocsBot AI': 'https://docsbot.ai',
  'Wonderchat': 'https://wonderchat.io',
  'Kommunicate': 'https://www.kommunicate.io',
  'Gorgias AI': 'https://www.gorgias.com',
  'DeepL': 'https://www.deepl.com',
  'Google Translate': 'https://translate.google.com',
  'Papago': 'https://papago.naver.com',
  'DeepL Write': 'https://www.deepl.com/write',
  'Grammarly Translate': 'https://www.grammarly.com',
  'Lokalise AI': 'https://lokalise.com',
  'Weglot': 'https://www.weglot.com',
  'Crowdin AI': 'https://crowdin.com',
  'Smartcat': 'https://www.smartcat.com',
  'Phrase': 'https://phrase.com',
  'HeyGen Video Translate': 'https://www.heygen.com/translate',
  'ElevenLabs Dubbing': 'https://elevenlabs.io/dubbing',
  'Maestra': 'https://maestra.ai',
  'Sonix': 'https://sonix.ai',
  'Interior AI': 'https://interiorai.com',
  'RoomGPT': 'https://www.roomgpt.io',
  'ReimagineHome': 'https://www.reimaginehome.ai',
  'Planner 5D AI': 'https://planner5d.com',
  'Homestyler AI': 'https://www.homestyler.com',
  'DecorMatters': 'https://decormatters.com',
  'Spacely AI': 'https://www.spacely.ai',
  'Architechtures': 'https://architechtures.com',
  'Maket AI': 'https://www.maket.ai',
  'TestFit': 'https://www.testfit.io',
  'Kaedim': 'https://www.kaedim3d.com',
  'Meshy': 'https://www.meshy.ai',
  'Luma AI': 'https://lumalabs.ai',
  'Spline AI': 'https://spline.design',
  'Masterpiece X': 'https://www.masterpiecex.com',
  'Alpha3D': 'https://www.alpha3d.io',
  'Tripo AI': 'https://www.tripo3d.ai',
  'CSM AI': 'https://www.csm.ai',
  'NVIDIA Omniverse': 'https://www.nvidia.com/en-us/omniverse/',
  'Scenario': 'https://www.scenario.com',
  'Shopify Magic': 'https://www.shopify.com/magic',
  'Shopify Sidekick': 'https://www.shopify.com/magic',
  'Claid.ai': 'https://claid.ai',
  'Prisync AI': 'https://prisync.com',
  'Octane AI': 'https://www.octaneai.com',
  'Clerk.io': 'https://www.clerk.io',
  'Nosto': 'https://www.nosto.com',
  'Zillow AI': 'https://www.zillow.com',
  'Redfin AI': 'https://www.redfin.com',
  'Restb.ai': 'https://restb.ai',
  'Epique AI': 'https://epique.ai',
  'ListingAI': 'https://listingai.co',
  'Write.homes': 'https://write.homes',
  'Virtual Staging AI': 'https://www.virtualstagingai.app',
  'Styldod': 'https://www.styldod.com',
  'BoxBrownie': 'https://www.boxbrownie.com',
  'Matterport': 'https://matterport.com',
  'Placer.ai': 'https://www.placer.ai',
  'Localo': 'https://localo.com',
  'BrightLocal': 'https://www.brightlocal.com',
  'Birdeye AI': 'https://birdeye.com',
  'Podium AI': 'https://www.podium.com',
  'Yext AI': 'https://www.yext.com',
  'Obsidian AI 플러그인': 'https://obsidian.md',
  'Mem AI': 'https://mem.ai',
  'Reflect AI': 'https://reflect.app',
  'Evernote AI': 'https://evernote.com',
  'Coda AI': 'https://coda.io',
  'ClickUp AI': 'https://clickup.com',
  'Asana AI': 'https://asana.com',
  'Monday AI': 'https://monday.com',
  'Trello AI': 'https://trello.com',
  'Slack AI': 'https://slack.com',
  'Google Gemini Workspace': 'https://workspace.google.com/solutions/ai/',
  'Superhuman AI': 'https://superhuman.com',
  'Shortwave AI': 'https://www.shortwave.com',
  'Motion': 'https://www.usemotion.com',
  'Reclaim AI': 'https://reclaim.ai',
  'Sunsama': 'https://www.sunsama.com',
  'Akiflow': 'https://akiflow.com',
  'Khanmigo': 'https://www.khanmigo.ai',
  'Duolingo Max': 'https://www.duolingo.com',
  'Quizlet AI': 'https://quizlet.com',
  'MagicSchool AI': 'https://www.magicschool.ai',
  'Eduaide.AI': 'https://www.eduaide.ai',
  'Curipod': 'https://curipod.com',
  'Socratic': 'https://socratic.org',
  'Photomath': 'https://photomath.com',
  'Wolfram Alpha': 'https://www.wolframalpha.com',
  'Elsa Speak': 'https://elsaspeak.com',
  'Speak': 'https://www.speak.com',
  'TutorAI': 'https://www.tutorai.me',
  'Coursebox AI': 'https://www.coursebox.ai',
  'LearnWorlds AI': 'https://www.learnworlds.com',
};

let src = fs.readFileSync(FILE, 'utf8');
const unmapped = new Set();
let replaced = 0;

src = src.replace(
  /(name: '((?:[^'\\]|\\.)*)',[\s\S]*?websiteUrl: ')https:\/\/google\.com\/search\?q=[^']*(')/g,
  (full, prefix, name, suffix) => {
    const url = URL_MAP[name];
    if (!url) {
      unmapped.add(name);
      return full;
    }
    replaced += 1;
    return prefix + url + suffix;
  },
);

fs.writeFileSync(FILE, src, 'utf8');
console.log(`Replaced ${replaced} websiteUrl values.`);
if (unmapped.size > 0) {
  console.log('UNMAPPED NAMES:');
  for (const name of unmapped) console.log(' -', name);
}
const remaining = (src.match(/google\.com\/search/g) || []).length;
console.log(`Remaining google.com/search links: ${remaining}`);
