const fs = require('fs');
const path = require('path');

const planPath = 'C:\\Users\\hijac\\.gemini\\antigravity\\brain\\aeeffbf2-7f7f-4937-b3e9-a2ac18f4bbac\\category_plan.md';
const outputPath = path.join(__dirname, '..', 'src', 'data', 'generatedTools.ts');

const content = fs.readFileSync(planPath, 'utf-8');

// Regex to match category blocks:
// ### 1. Chatbots & Assistants (챗봇 및 비서)
// ...
// - **도구 리스트**: ChatGPT, Claude, ...
const categoryRegex = /###\s+\d+\.\s+([^\(]+)\(([^\)]+)\)[\s\S]*?\-\s+\*\*도구 리스트\*\*:\s+([^\n]+)/g;

let match;
const generatedTools = [];

// Map category names to categoryIds
const categoryIdMap = {
  'Chatbots & Assistants ': 'chatbots',
  'Writing & Copywriting ': 'writing',
  'Research & Search ': 'research',
  'Image Generation & Editing ': 'image-generation',
  'Design & UI ': 'design-ui',
  'Video Generation & Editing ': 'video-generation',
  'Voice & Text-to-Speech ': 'audio-voice',
  'Music & Audio ': 'music-audio',
  'Coding, Dev & APIs ': 'coding-dev',
  'No-Code & Website Builders ': 'no-code',
  'Automation & Agents ': 'automation',
  'Meeting & Transcription ': 'meeting',
  'Presentation, Documents & Legal ': 'presentation-docs',
  'Marketing & SEO ': 'marketing-seo',
  'Data Analysis & Spreadsheets ': 'data-analysis',
  'Customer Support ': 'customer-support',
  'Translation & Localization ': 'translation',
  '3D & Architecture ': '3d-architecture',
  'E-commerce, Local & Business ': 'ecommerce-business',
  'Productivity, Education & Notes ': 'productivity-education'
};

const makeSlug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

let count = 0;

while ((match = categoryRegex.exec(content)) !== null) {
  const catNameEn = match[1];
  const catNameKo = match[2];
  const toolsStr = match[3];

  const catId = categoryIdMap[catNameEn] || 'misc';
  const toolNames = toolsStr.split(',').map(t => t.trim()).filter(Boolean);

  toolNames.forEach(name => {
    count++;
    const slug = makeSlug(name);
    
    generatedTools.push(`
  {
    id: '${slug}',
    name: '${name.replace(/'/g, "\\'")}',
    slug: '${slug}',
    description: {
      en: 'AI tool for ${catNameEn.trim().toLowerCase()}.',
      ko: '${catNameKo.trim()} 관련 AI 도구입니다.'
    },
    longDescription: {
      en: '${name.replace(/'/g, "\\'")} is an AI tool designed for ${catNameEn.trim().toLowerCase()}. It provides essential features to help users automate and improve their workflows.',
      ko: '${name.replace(/'/g, "\\'")} 도구는 ${catNameKo.trim()} 작업을 지원하는 AI 서비스입니다. 사용자의 워크플로를 자동화하고 향상시킬 수 있는 핵심 기능을 제공합니다.'
    },
    websiteUrl: 'https://google.com/search?q=${encodeURIComponent(name)}+AI',
    categoryId: '${catId}',
    pricingType: 'Freemium',
    rating: 4.5,
    beginnerFriendly: true,
    koreanSupport: false,
    mobileSupport: true,
    commercialUse: false,
    featured: false,
    tags: ['ai', '${catId}'],
    features: [
      { en: 'Core functionality', ko: '핵심 기능' },
      { en: 'AI automation', ko: 'AI 자동화' }
    ],
    pros: [
      { en: 'Easy to use', ko: '사용하기 쉬움' }
    ],
    cons: [
      { en: 'Pricing details vary', ko: '요금제 확인 필요' }
    ],
    useCases: [
      { en: 'General usage', ko: '일반적인 작업 활용' }
    ]
  }`);
  });
}

const fileContent = `import { Tool } from '../types';

// This file is auto-generated by scripts/generate_mvp_tools.js
export const generatedTools: Tool[] = [${generatedTools.join(',')}
];
`;

fs.writeFileSync(outputPath, fileContent, 'utf-8');
console.log(`Successfully generated ${count} tools in src/data/generatedTools.ts`);
